---
regions:
- "global" # This is for all global resource types e.g. IAM
# - "eu-west-1"

account-blocklist:
- 1234567890

# optional: restrict nuking to these resources
# resource-types:
#   targets:
#   - IAMUser
#   - IAMUserPolicyAttachment
#   - IAMUserAccessKey
#   - S3Bucket
#   - S3Object
#   - Route53HostedZone
#   - EC2Instance
#   - CloudFormationStack
#   - MSKCluster

accounts:
  103334327501:
    filters:
      IAMUser:
      - "infra-nuke"
      IAMUserPolicyAttachment:
      - property: RoleName
        value: "AdministratorAccess"
      # IAMUserAccessKey:
      # - property: UserName
      #   value: "admin"
